### ISSUE TITLE
How can I use Kafka JCA into WebLogic server 12c?

### ISSUE THREAD

**Issue by Markovitz** [payara/Cloud-Connectors#112]
Hi,
Does it possible to use Kafka JCA into WebLogic server 12c. I installed this JCA and created MDB bean base on you description, but I stuck with configuration. 

Message icon - Error Error: The Message Driven Bean "KafkaPublisher(Application: MomXXX, EJBComponent: SoftMomXXX.jar)", does not have a message destination configured. The message destination must be set using a message-destination-link, destination-resource-link, destination-jndi-name or a resource-adapter-jndi-name. Ensure the Message Driven Bean (MDB) is mapped to a message destination. This can be done in the ejb-jar.xml descriptor by specifying a message-destination-link for the MDB. A message destination can be set in the weblogic-ejb-jar.xml inside the message-driven-descriptor element. Use the destination-resource-link to map the MDB to an application-scoped JMS destination. The destination-jndi-name element can be used to map the MDB to the JNDI name of a JMS destination. Finally, the resource-adapter-jndi-name element can be used to map the MDB to the JNDI name of a JCA resource adapter. Annotation can also be used instead of using above deployment descriptor.
Message icon - Error Substituted for missing class Error - The Message Driven Bean "KafkaPublisher(Application: MomXXX, EJBComponent: SoftMomXXX.jar)", does not have a message destination configured. The message destination must be set using a message-destination-link, destination-resource-link, destination-jndi-name or a resource-adapter-jndi-name. Ensure the Message Driven Bean (MDB) is mapped to a message destination. This can be done in the ejb-jar.xml descriptor by specifying a message-destination-link for the MDB. A message destination can be set in the weblogic-ejb-jar.xml inside the message-driven-descriptor element. Use the destination-resource-link to map the MDB to an application-scoped JMS destination. The destination-jndi-name element can be used to map the MDB to the JNDI name of a JMS destination. Finally, the resource-adapter-jndi-name element can be used to map the MDB to the JNDI name of a JCA resource adapter. Annotation can also be used instead of using above deployment descriptor. 

Does it possible to do it. Do you know how to prepare ejb-jar.xml or weblogic-ejb-jar.xml file for it, or how should I configure it on WebLogic server
Thanks

**Comment by smillidge** [comment]
The error messages imply it needs a JMS destination. However the Kafka adapter is not a JMS adapter. I suggest looking at the documentation on how to configure MDBs to work with JCA adapters.

**Comment by adisnuhan** [comment]
Hi Markovitz,

I'm facing the same issue like you are. Have you found a solution for this Problem?

Regards, 
Adis

**Comment by adisnuhan** [comment]
> Hi,
> Does it possible to use Kafka JCA into WebLogic server 12c. I installed this JCA and created MDB bean base on you description, but I stuck with configuration.
> 
> Message icon - Error Error: The Message Driven Bean "KafkaPublisher(Application: MomXXX, EJBComponent: SoftMomXXX.jar)", does not have a message destination configured. The message destination must be set using a message-destination-link, destination-resource-link, destination-jndi-name or a resource-adapter-jndi-name. Ensure the Message Driven Bean (MDB) is mapped to a message destination. This can be done in the ejb-jar.xml descriptor by specifying a message-destination-link for the MDB. A message destination can be set in the weblogic-ejb-jar.xml inside the message-driven-descriptor element. Use the destination-resource-link to map the MDB to an application-scoped JMS destination. The destination-jndi-name element can be used to map the MDB to the JNDI name of a JMS destination. Finally, the resource-adapter-jndi-name element can be used to map the MDB to the JNDI name of a JCA resource adapter. Annotation can also be used instead of using above deployment descriptor.
> Message icon - Error Substituted for missing class Error - The Message Driven Bean "KafkaPublisher(Application: MomXXX, EJBComponent: SoftMomXXX.jar)", does not have a message destination configured. The message destination must be set using a message-destination-link, destination-resource-link, destination-jndi-name or a resource-adapter-jndi-name. Ensure the Message Driven Bean (MDB) is mapped to a message destination. This can be done in the ejb-jar.xml descriptor by specifying a message-destination-link for the MDB. A message destination can be set in the weblogic-ejb-jar.xml inside the message-driven-descriptor element. Use the destination-resource-link to map the MDB to an application-scoped JMS destination. The destination-jndi-name element can be used to map the MDB to the JNDI name of a JMS destination. Finally, the resource-adapter-jndi-name element can be used to map the MDB to the JNDI name of a JCA resource adapter. Annotation can also be used instead of using above deployment descriptor.
> 
> Does it possible to do it. Do you know how to prepare ejb-jar.xml or weblogic-ejb-jar.xml file for it, or how should I configure it on WebLogic server
> Thanks

Hi Markovitz,

I'm facing the same issue like you are. Have you found a solution for this Problem?

Thanks in advance!

**Comment by antonio-petricca** [comment]
Same issue for me!

**Comment by fturizo** [comment]
Old issue that seems abandoned. Closed. If the issues are still present, please raise a request in the [Ecosystem Support repository](https://github.com/payara/ecosystem-support)
