### ISSUE TITLE
[BUG]Problem with onRecords

### ISSUE THREAD

**Issue by lukesrepo** [payara/Cloud-Connectors#138]
Previously have been using the _@OnRecord_ semantics to process idividual records.
Now the project goual would be to use the _@OnRecord**s**_ semantics to process the polled records in batches. 

However the small return statement(see [here](https://github.com/payara/Cloud-Connectors/blob/165b260244beeec6e437b74e6e7bb26947ce67f9/Kafka/KafkaJCAAPI/src/main/java/fish/payara/cloud/connectors/kafka/inbound/KafkaAsynchWorker.java#L179)), instead of a simple break (analog to [here](https://github.com/payara/Cloud-Connectors/blob/master/Kafka/KafkaJCAAPI/src/main/java/fish/payara/cloud/connectors/kafka/inbound/KafkaAsynchWorker.java#L196)) causes only the first portion of records to be processed. 

This seems to be a trivial bug, not even sure if the PR and the papaerwork would be worth starting here.

**Comment by smillidge** [comment]
Thanks for the report. You don't need paperwork for a very simple PR.

**Comment by fturizo** [comment]
Old issue that seems abandoned. Closed. If the issues are still present, please raise a request in the [Ecosystem Support repository](https://github.com/payara/ecosystem-support). You can still make a PR to this repo if you want still to contribute to the repository
