### ISSUE TITLE
Unable to fetch KafkaRARAPI from Maven

### ISSUE THREAD

**Issue by abhirockzz** [payara/Cloud-Connectors#16]
`<dependency>
            <groupId>fish.payara.cloud.connectors.kafka</groupId>
            <artifactId>KafkaRARAPI</artifactId>
            <version>0.1.0-SNAPSHOT</version>
            <type>jar</type>
            <scope>provided</scope>
        </dependency>`

The above co-ordinates don't work. Error: _Could not find artifact fish.payara.cloud.connectors.kafka:KafkaRARAPI:jar:0.1.0-SNAPSHOT

**Comment by smillidge** [comment]
The initial 0.1 release will be uploaded to maven central soon. At the moment you need to build the connectors using maven directly.

**Comment by smillidge** [comment]
0.1.0 are now on Maven central
