### ISSUE TITLE
Clarify 'pollInterval' ActivationConfigProperty

### ISSUE THREAD

**Issue by abhirockzz** [payara/Cloud-Connectors#18]
Is this really an interval ? As far as the usage is concerned, it's used as a poll timeout https://github.com/payara/Cloud-Connectors/blob/master/Kafka/KafkaRAR/src/main/java/fish/payara/cloud/connectors/kafka/inbound/KafkaPoller.java#L77

This should either be renamed or the semantics should be clarified

**Comment by smillidge** [comment]
Currently it is used as both as the timeout of the call to poll on Kafka but also as how often the TimerTask is calls poll. These can probably be split out.

**Comment by fturizo** [comment]
Old issue seems to be abandoned. Closing
