### ISSUE TITLE
Inbound Kafka MDB not working in Payara Micro

### ISSUE THREAD

**Issue by abhirockzz** [payara/Cloud-Connectors#19]
Tried with a (dockerized) Payara Micro setup - https://github.com/abhirockzz/payara-kafka-mdb. I do not see the expected messages being received in the MDB. Can you please confirm if I am missing something

**Comment by smillidge** [comment]
I can't see anything obvious. Does the example MDB https://github.com/payara/Cloud-Connectors/tree/master/Kafka/KafkaExample work for you outside of Docker?

**Comment by abhirockzz** [comment]
Yes. It works outside of Docker. I was using the `[payara/micro](https://github.com/abhirockzz/payara-kafka-mdb/blob/master/Dockerfile#L1)` Docker image and this is the version which its using - `Payara Micro  4.1.1.171 #badassmicrofish (build 137)`. I tried this without Docker using the Payara Micro JAR from [Maven](https://mvnrepository.com/artifact/fish.payara.extras/payara-micro/4.1.2.172) and it works - both local and Docker mode

**Comment by mikecroft** [comment]
The `LATEST` tag in docker hub should now contain 172

**Comment by abhirockzz** [comment]
Yeah. I see that it was updated few hours ago and I actually tried it some time back. For some reason it doesn't work. On the other hand, I built another Docker image (copied the downloaded Payara Micro 172 from Maven in the Dockerfile) - this worked fine.  Not sure what I am missing

**Comment by smillidge** [comment]
171 wouldn't work as the functionality to support JCA connectors and MDBs was added to Patara Micro 172
