### ISSUE TITLE
Update Kafka-Client to latest 0.10.x

### ISSUE THREAD

**Issue by svendiedrichsen** [payara/Cloud-Connectors#22]
Feature request:

We are planning on using this adapter for transferring Avro messages but the Confluence platform 3.2.x we are using needs a Kafka-Client 0.10.x. Would it be possible to upgrade to the latest 0.10.x kafka client library?

**Comment by smillidge** [comment]
Could you sign a CLA then we can take your PRs? https://github.com/payara/Payara/blob/master/PayaraCLA.pdf

**Comment by smillidge** [comment]
Fixed by #23
