### ISSUE TITLE
Allow Kafka connector to receive generic additonal config properties

### ISSUE THREAD

**Issue by svendiedrichsen** [payara/Cloud-Connectors#24]
When using the KafkaConnector with i.e. Confluent KafkaAvroSerializer you need to pass an additional property 'schema.registry.url' which specifies a list of URLs for the (de)serializer to contact the schema registry.

Please see here:
http://docs.confluent.io/current/schema-registry/docs/serializer-formatter.html

I would like to propose and if acceptable also implement an 'additionalProperties' property to the KafkaManagedConnectionFactory. It should be parsed as a comma separated key/value list. Those additonal properties should be added to the original properties.

**Comment by smillidge** [comment]
Sounds good. Please create a PR from your branch. Also as I mentioned on your previous PR we need a signed CLA to merge your PRs.

**Comment by svendiedrichsen** [comment]
I have just send the signed CLA via email to cla@payara.org. Please consider the PR #23.

**Comment by smillidge** [comment]
Fixed by #23
