### ISSUE TITLE
Kafka Connector: Every connection contains its own KafkaProducer

### ISSUE THREAD

**Issue by svendiedrichsen** [payara/Cloud-Connectors#25]
I was trying to use the Kafka-Connector but failed to make it work. After reading through the sources I found that every connection contains its own KafkaProducer and upon closing the connection it closes the producer. My problem was that I have a linger time configured and the connection gets closed before the linger time is up.
* KafkaProducer is thread-safe and thus can be used by multiple connections
* each producer contains some significant amount of buffer to handle sending several messages in one buffer and some managment thread to handle sending. This makes it pretty heavy-weight and closing it when closing the connection wastes resources needlessly
* creating several producers from the same properties makes the JMX monitoring beans within them fail to register. They will all try to use the same id.

I'd suggest to have one KafkaProducer per ConnectionFactory which then needs some way of closing the factory.
Closing the connection should not close the producer which should be lended to them.

@smillidge: What do you think?

**Comment by smillidge** [comment]
The Connections should be pooled in the JCA Connection Factory so closing a connection at the application level shouldn't result in closing the KafkaProducer. I'll take a look to see if it is a bug.

**Comment by svendiedrichsen** [comment]
Closing the connection at application level only disassociates it from the managed connection as far as I can see. My problem seems to be something else. But nevertheless can one producer per managed connection create a lot of producers. Depending on the poolsize obviously.

**Comment by smillidge** [comment]
It should be one Producer per Connection and therefore limited by Connection Pool Size. I see the point RE: JMX. The model could be changed to one Producer per Connection Factory. Do you have a simple test case that shows Producers being closed? If not I will build a simple test myself.

**Comment by svendiedrichsen** [comment]
I'm on vacation until 15th of july. Will try to find out why no messages are sent afterwards.

**Comment by smillidge** [comment]
I've moved the Producer to the Connection Factory.

Tested with ab to hit the new example REST endpoint
```ab -u /tmp/text -T 'application/json' -n 100000 -c 20  http://MintyFresh:8080/kafka-rest-example-0.2.0-SNAPSHOT/kafka/queues/test```

Pushed 5600 per second and heap dump confirms only 1 instance of ```KafkaProducer``` created and 20 instances of ```ManagedConnection```

**Comment by svendiedrichsen** [comment]
That's excellent work. Thank you very much.

**Comment by smillidge** [comment]
You can deploy the configuration as shown in the example projects.
