### ISSUE TITLE
Custom Connection Factories

### ISSUE THREAD

**Issue by MattGill98** [payara/Cloud-Connectors#26]
Not sure whether this would make sense or not (more of a suggestion), but would it be possible to have a subclass of `@ConnectionFactoryDefinition` for each project? Because it seems annoying that things like the AWS access key ID are in the properties section of the connection factory definition, since that makes them seem optional. Also as the connection factory interface name will always be the same, that could maybe be constant/removed? Is this functionality even possible?

**Comment by smillidge** [comment]
It would be custom code and Payara Specific. ConnectionFactoryDefinition is a standard JavaEE annotation and so will work in all application servers.

**Comment by MattGill98** [comment]
I don't believe it would be Payara specific, just specific to this library. E.g. instead of
~~~~
@ConnectionFactoryDefinition(name = "java:comp/env/SQSConnectionFactory",
        description = "SQS Connection Factory",
        interfaceName = "fish.payara.cloud.connectors.amazonsqs.api.AmazonSQSConnectionFactory",
        resourceAdapter = "amazon-sqs-rar-0.1.0",
        minPoolSize = 15,
        maxPoolSize = 30,
        transactionSupport = TransactionSupport.TransactionSupportLevel.NoTransaction,
        properties = {
            "awsAccessKeyId=${ENV=awsAccessKey}",
            "awsSecretKey=${ENV=awsSecretKey}",
            "region=eu-west-2"
        })
~~~~
you could have: 
~~~~
@SQSConnectionFactoryDefinition(name = "java:comp/env/SQSConnectionFactory",
        description = "SQS Connection Factory",
        resourceAdapter = "amazon-sqs-rar-0.1.0",
        minPoolSize = 15,
        maxPoolSize = 30,
        transactionSupport = TransactionSupport.TransactionSupportLevel.NoTransaction,
        awsAccessKeyId = "${ENV=awsAccessKey}",
        awsSecretKey = "${ENV=awsSecretKey}",
        awsRegion = "eu-west-2"
        })
~~~~
