### ISSUE TITLE
Message acknowledge

### ISSUE THREAD

**Issue by jeromeky** [payara/Cloud-Connectors#30]
Hi there,

I'm currently using the SQS Message (com.amazonaws.services.sqs.model)

Is there a way to manually acknowledge / refuse a message so it's going back to the queue ?

So far I have to throw an exception to put it back to the queue.

Thanks.

**Comment by smillidge** [comment]
Can you describe a bit more what sort of api you would like?

**Comment by jeromeky** [comment]
Hi Steve,

To be able to do something like that
```
@OnSQSMessage
public void receiveMessage(Message message) {
    if(success()) {
        message.acknowledge();
        System.out.println("Message " + message.getBody() + " was acknowledge and is deleted");
        return;
    }
    System.out.println("Message " + message.getBody() + " was not acknowledged and is going back to the queue");
}
```

**Comment by fturizo** [comment]
Old issue that seems abandoned. Closed.
