### ISSUE TITLE
SQS connector polling is stopped by temporary network issues

### ISSUE THREAD

**Issue by bbulk** [payara/Cloud-Connectors#37]
Hi,

I am using the latest repository version 0.3.0-SNAPSHOT of the connector and the current Payara 174.

Every time there is a short (just a few seconds) network/DNS issue, a `com.amazonaws.SdkClientException` (caused by a `java.net.UnknownHostException`) is thrown and I have to restart the application to poll for messages again.

One example stacktrace:
[UnknownHostException.txt](https://github.com/payara/Cloud-Connectors/files/1623338/UnknownHostException.txt)

It is also reproducable with other kinds of network exceptions, like unplugging the machine for a few seconds.

Best Regards
Ben

**Comment by smillidge** [comment]
oops missed this one we'll get on it
