### ISSUE TITLE
Provide SQS JMS adapter

### ISSUE THREAD

**Issue by candrews** [payara/Cloud-Connectors#38]
Would it not be better to implement AmazonSQSJCAAPI using JMS, abstracting SQS from the perspective of the JEE application? (That way, existing applications can be easy changed to use SQS if they're already using JMS, and it allows for moving between JMS implementations easily.) You could use the Amazon SQS Java Messaging Library https://github.com/awslabs/amazon-sqs-java-messaging-lib making the effort more maintainable and less tedious.

I'm attempting to do that now: https://github.com/candrews/sqs-jms-ra - please feel free to grab this code and add to the Payara adapter library or contribute to my work.

**Comment by smillidge** [comment]
Hi that is a great idea just a lot more work!

If you want to contribute to the project please do and we can incorporate it into the adapter library. We would need a signed CLA.

**Comment by baztian** [comment]
@candrews, I really like your idea. Also I've tried your project successfully.

@smillidge why is it "a lot more work" @candrews  code base is very small.

Usage of amazon-sqs-java-messaging-lib might be a good starting point. But it doesn't seem to being actively developed anymore. Further on I had some trouble in the past with it. On stackoverflow it is often recommended to write your own code insted of using the lib. aws sqs api from sdk isn't that hard and I don't think that much code is needed.

**Comment by fturizo** [comment]
Old issue that seems abandoned. Closed.
