### ISSUE TITLE
Cannot Pull Down 2.0 Artifacts MQTT, SQS, From Maven Repository http://mvnrepository.com

### ISSUE THREAD

**Issue by oxley-calabrio** [payara/Cloud-Connectors#39]
I am creating a small project by using the latest MQTT Artifacts available.  When I try to down the MQTT API artifact, it fails indicating that it cannot parse the POM correctly and trying to find a Cloud-Connector that does not exist.

When I clone your GIT Repo locally and compile from the root directory, I successfully build every project.  Of course, now that I have it in my .m2 directory, my project can find MQTT API Artifact and the compile successfully.

I tried it with multiple artifacts and I think Kafka is the only one that successfully can pull down the jar from Maven remotely.  I do not have a problem with going to Maven http://mvnrepository.com because I can pull down Payara Micro successfully.

Easiest steps to reproduce:
1)  Blow away your local .m2 fish/payara/cloud
2)  Navigate to MQTTJCAAPI directory
3)  Try to issue a Maven build there.  It should fail with the Cloud Connector error.

If this does not help, I will try to copy and paste the console output.

**Comment by mikecroft** [comment]
What is the  cloud connector error you see? MQTT 0.2.0 is in Maven just as Kafka is in Maven, so there should be no difference. How are your dependencies configured in your pom.xml?

**Comment by oxley-calabrio** [comment]
Sorry, I wrote the wrong one to induce the error.  Navigate to MQTTRAR and try to compile and you will see the error I am receiving in my project:

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building MQTT JCA Adapter RAR 0.2.0
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/fish/payara/cloud/connectors/mqtt/mqtt-jca-api/0.2.0/mqtt-jca-api-0.2.0.pom
Downloaded: https://repo.maven.apache.org/maven2/fish/payara/cloud/connectors/mqtt/mqtt-jca-api/0.2.0/mqtt-jca-api-0.2.0.pom (3 KB at 3.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/fish/payara/cloud/connectors/cloud-connectors/0.2.0/cloud-connectors-0.2.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.721 s
[INFO] Finished at: 2018-02-21T08:19:44-06:00
[INFO] Final Memory: 12M/243M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project mqtt-rar: Could not resolve dependencies for project fish.payara.cloud.connectors.mqtt:mqtt-rar:rar:0.2.0: Failed to collect dependencies at fish.payara.cloud.connectors.mqtt:mqtt-jca-api:jar:0.2.0: Failed to read artifact descriptor for fish.payara.cloud.connectors.mqtt:mqtt-jca-api:jar:0.2.0: Could not find artifact fish.payara.cloud.connectors:cloud-connectors:pom:0.2.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException


I am using Gradle.  I tried compile, providedCompile, and what it should be compileOnly:

> Could not resolve all dependencies for configuration ':compileOnly'.
   > Could not resolve fish.payara.cloud.connectors.mqtt:mqtt-jca-api:0.2.0.
     Required by:
         project :
      > Could not resolve fish.payara.cloud.connectors.mqtt:mqtt-jca-api:0.2.0.
         > Could not parse POM C:\Users\Josh.Oxley\.m2\repository\fish\payara\cloud\connectors\mqtt\mqtt-jca-api\0.2.0\mqtt-jca-api-0.2.0.pom
            > Could not find fish.payara.cloud.connectors:cloud-connectors:0.2.0.
              Searched in the following locations:
                  file:/C:/Users/Josh.Oxley/.m2/repository/fish/payara/cloud/connectors/cloud-connectors/0.2.0/cloud-connectors-0.2.0.pom
                  file:/C:/Users/Josh.Oxley/.m2/repository/fish/payara/cloud/connectors/cloud-connectors/0.2.0/cloud-connectors-0.2.0.jar
                  https://repo1.maven.org/maven2/fish/payara/cloud/connectors/cloud-connectors/0.2.0/cloud-connectors-0.2.0.pom
                  https://repo1.maven.org/maven2/fish/payara/cloud/connectors/cloud-connectors/0.2.0/cloud-connectors-0.2.0.jar
                  https://mvnrepository.com/fish/payara/cloud/connectors/cloud-connectors/0.2.0/cloud-connectors-0.2.0.pom
                  https://mvnrepository.com/fish/payara/cloud/connectors/cloud-connectors/0.2.0/cloud-connectors-0.2.0.jar
      > Could not resolve fish.payara.cloud.connectors.mqtt:mqtt-jca-api:0.2.0.
         > Could not parse POM https://repo1.maven.org/maven2/fish/payara/cloud/connectors/mqtt/mqtt-jca-api/0.2.0/mqtt-jca-api-0.2.0.pom
            > Could not find fish.payara.cloud.connectors:cloud-connectors:0.2.0.

**Comment by mikecroft** [comment]
Why are you trying to build the RAR file? The RARs for each API artefact are available on Maven central.

**Comment by oxley-calabrio** [comment]
I am unable to pull from Maven Central in my main project.  Even your MQTTRAR is unable to pull from Maven Central.

**Comment by oxley-calabrio** [comment]
It looks like I missed this nugget in the instructions:

[https://docs.payara.fish/documentation/ecosystem/cloud-connectors/cloud-connectors.html](url)

> Cloud connectors are currently not available in binary form, but have to be built from source...

**Comment by smillidge** [comment]
They should be there see http://search.maven.org/#artifactdetails%7Cfish.payara.cloud.connectors.mqtt%7Cmqtt-rar%7C0.2.0%7Crar

**Comment by oxley-calabrio** [comment]
I agree that it should but the project is looking for this in central:

>fish.payara.cloud.connectors:cloud-connectors:pom:0.2.0

**Comment by mikecroft** [comment]
@MattGill98 had a look into this - it seems the API poms erroneously have a <parent> tag in all but the Kafka API, so each looks for the cloud-connectors parent. A JIRA has been created to correct the poms.

**Comment by Pandrex247** [comment]
The parent POM for 0.2.0 is now available in Maven Central.
