### ISSUE TITLE
Azure Service Bus Connector not working on Payara Server 181

### ISSUE THREAD

**Issue by anaelcarvalho** [payara/Cloud-Connectors#42]
Hello -

Tried to run the example available at the [documentation page](https://docs.payara.fish/documentation/ecosystem/cloud-connectors/cloud-connectors.html) with Payara Server 181 with the steps below:

`./asadmin start-domain domain1`
`./asadmin deploy {path}/Cloud-Connectors/AzureServiceBus/AzureSBRAR/target/azure-sb-rar-0.3.0-SNAPSHOT.rar`
`./asadmin deploy {path}/Cloud-Connectors/AzureServiceBus/AzureSBExample/target/azure-sb-example-0.3.0-SNAPSHOT.jar`

The deploy of the sample application fails with the error below, however:

> [2018-03-07T20:12:33.931-0300] [Payara 4.1] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=110 _ThreadName=admin-thread-pool::admin-listener(2)] [timeMillis: 1520464353931] [levelValue: 1000] [[
>   Exception while loading the app : EJB Container initialization error
> java.lang.IllegalArgumentException: [fish.payara.cloud.connectors.azuresb.api.AzureSBConnectionFactory] is not an allowed property value type
> 	at com.sun.enterprise.deployment.ResourceReferenceDescriptor.checkType(ResourceReferenceDescriptor.java:577)
> 	at com.sun.enterprise.container.common.impl.ComponentEnvManagerImpl.addResourceReferences(ComponentEnvManagerImpl.java:505)
> 	at com.sun.enterprise.container.common.impl.ComponentEnvManagerImpl.addJNDIBindings(ComponentEnvManagerImpl.java:605)
> 	at com.sun.enterprise.container.common.impl.ComponentEnvManagerImpl.bindToComponentNamespace(ComponentEnvManagerImpl.java:197)
> 	at com.sun.ejb.containers.BaseContainer.setupEnvironment(BaseContainer.java:3993)
> 	at com.sun.ejb.containers.BaseContainer.<init>(BaseContainer.java:867)
> 	at com.sun.ejb.containers.StatelessSessionContainer.<init>(StatelessSessionContainer.java:145)
> 	at com.sun.ejb.containers.StatelessSessionContainer.<init>(StatelessSessionContainer.java:139)
> 	at com.sun.ejb.containers.StatelessContainerFactory.createContainer(StatelessContainerFactory.java:61)
> 	at org.glassfish.ejb.startup.EjbApplication.loadContainers(EjbApplication.java:225)
> 	at org.glassfish.ejb.startup.EjbDeployer.load(EjbDeployer.java:290)
> 	at org.glassfish.ejb.startup.EjbDeployer.load(EjbDeployer.java:100)
> 	at org.glassfish.internal.data.ModuleInfo.load(ModuleInfo.java:209)
> 	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:318)
> 	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:497)
> 	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
> 	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:508)
> 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:544)
> 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:540)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at javax.security.auth.Subject.doAs(Subject.java:360)
> 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:539)
> 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:570)
> 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:562)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at javax.security.auth.Subject.doAs(Subject.java:360)
> 	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:561)
> 	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1469)
> 	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:111)
> 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1851)
> 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1727)
> 	at org.glassfish.admin.rest.resources.admin.CommandResource.executeCommand(CommandResource.java:407)
> 	at org.glassfish.admin.rest.resources.admin.CommandResource.execCommandSimpInMultOut(CommandResource.java:234)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
> 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
> 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
> 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
> 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
> 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
> 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
> 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
> 	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
> 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
> 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
> 	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
> 	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
> 	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
> 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
> 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
> 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
> 	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384)
> 	at org.glassfish.admin.rest.adapter.JerseyContainerCommandService$3.service(JerseyContainerCommandService.java:173)
> 	at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:179)
> 	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:483)
> 	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:180)
> 	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
> 	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
> 	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
> 	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
> 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
> 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
> 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
> 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
> 	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
> 	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:539)
> 	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
> 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
> 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
> 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
> 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
> 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
> 	at java.lang.Thread.run(Thread.java:745)
> ]]

Is this known? The example appears to run fine with Payara Micro 181, though.

Thank you!

**Comment by smillidge** [comment]
Hi on Payara Server you need to set the classloading policy for the Connector Service to be global (see below for the asadmin command). This has already been done on Payara Micro out of the box.

```
asadmin> set configs.config.server-config.connector-service.class-loading-policy=global
```

If you are not deploying to the DAS change `server-config` above into the config your servers are using.

**Comment by brunovalentim-saraiva** [comment]
Amazing, Thanks for your time.

**Comment by anaelcarvalho** [comment]
Works fine now, thanks!
