### ISSUE TITLE
missing ra.xml?

### ISSUE THREAD

**Issue by calmenergy** [payara/Cloud-Connectors#55]
The rar files produced by these builds do not seem to include ra.xml files.

**Comment by MattGill98** [comment]
Hi @calmenergy,

Since JCA 1.6 the ra.xml is no longer required. See [here](https://docs.oracle.com/cd/E24329_01/web.1211/e24971/creating.htm#ADAPT313) for more information.

Kind regards,

Matt

**Comment by calmenergy** [comment]
Thanks; I missed that.
