### ISSUE TITLE
Question about the ConsumerRecord Class

### ISSUE THREAD

**Issue by MrConjurer** [payara/Cloud-Connectors#57]
Hi,

i have a question to the Payara Micro JCA Adapters, so in detail what is the best way to work with the ConsumerRecord.
I read messages with the Payara Micro JCA Adapters the result is a ConsumerRecord. In the ConsumerRecord i have access to the value(ConsumerRecord.value) from the message.
The message in the kafka topics look like this => {"state1":{"int":1},"state2":{"int":"0"}}. So it is a afro message.
What is the best way to work with the input of the value. If it will be a json message, so i can use a json parser.
I find a avro parser Framework like this Schema.Parser (Apache Avro Java 1.8.2 API). But im not shure the the result of the ConsumerRecord.value is really a avro message.
Can you help me?

**Comment by MrConjurer** [comment]
Or other try to explain my Question:
Can i use for example an other keyDeserializer and valueDeserializer.
Can i use this one org.apache.kafka.connect.json.JsonDeserializer or io.confluent.kafka.serializers.KafkaAvroDeserializer?

**Comment by peteral** [comment]
Hi MrConjurer,

Avro is a binary format so unless you parsed the message using Avro and then displayed as JSON I am pretty sure this is just plain JSON. The JsonDeserializer from Kafka Connect might just work for you.

You can use another key and value deserializer by setting the corresponding ActivationConfigProperties (I assume, you are using the inbound resource adapter).

Example using Avro Deserializer from Confluent:

```java
@MessageDriven(activationConfig = {
        @ActivationConfigProperty(propertyName = "clientId", propertyValue = "xxx"),
        @ActivationConfigProperty(propertyName = "groupIdConfig", propertyValue = "xxxGroup"),
        @ActivationConfigProperty(propertyName = "autoCommitInterval", propertyValue = "100"),
        @ActivationConfigProperty(propertyName = "retryBackoff", propertyValue = "1000"),
        @ActivationConfigProperty(propertyName = "keyDeserializer", propertyValue = "org.apache.kafka.common.serialization.StringDeserializer"),
        @ActivationConfigProperty(propertyName = "valueDeserializer", propertyValue = "io.confluent.kafka.serializers.KafkaAvroDeserializer"),
        @ActivationConfigProperty(propertyName = "pollInterval", propertyValue = "3000"),
        @ActivationConfigProperty(propertyName = "topics", propertyValue = "inbound"),
        @ActivationConfigProperty(propertyName = "bootstrapServersConfig", propertyValue = "broker:29092"),
        @ActivationConfigProperty(propertyName = "additionalProperties", propertyValue = "schema.registry.url=http://registry:8081")
        })
@ResourceAdapter("kafka-rar")
public class KafkaListenerBean implements KafkaListener {
```

**Comment by MrConjurer** [comment]
Hi peteral,
thanks for your answer. I'll try to describe my problem in more detail.
I have a Mysql DB with it and the jdbc connector i write to a kafka topic.
I tried 3 connector configs. Here ar the configs:
{
"name": "jdbc_source_mysql_avro_01",
"config": 	{
                "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
                "key.converter": "io.confluent.connect.avro.AvroConverter",
                "key.converter.schema.registry.url": "http://localhost:8081",
                "value.converter": "io.confluent.connect.avro.AvroConverter",
                "value.converter.schema.registry.url": "http://localhost:8081",
                "connection.url": "",
                "table.whitelist": "test",
                "mode": "timestamp",
                "timestamp.column.name": "update_ts",
                "validate.non.null": "false",
                "topic.prefix": "avor-"
			}
}

{
"name": "jdbc_source_mysql_json_02",
"config": 	{
                "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
			     "key.converter": "org.apache.kafka.connect.json.JsonConverter",
                "key.converter.schemas.enable":"true",
                "value.converter": "org.apache.kafka.connect.json.JsonConverter",
                "value.converter.schemas.enable": "true",
                "connection.url": "",
                "table.whitelist": "test",
                "mode": "timestamp",
                "timestamp.column.name": "update_ts",
                "validate.non.null": "false",
                "topic.prefix": "json-"
			}
}

{
"name": "jdbc_source_mysql_string_03",
"config": 	{
                "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
			    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
                "key.converter.schemas.enable":"true",
                "value.converter": "org.apache.kafka.connect.storage.StringConverter",
                "value.converter.schemas.enable": "true",
                "connection.url": "",
                "table.whitelist": "test",
                "mode": "timestamp",
                "timestamp.column.name": "update_ts",
                "validate.non.null": "false",
                "topic.prefix": "string-"
			}
}

Then i have this kafkaMDB Class.
And i change the keyDeserializer and the valueDeserializer and test it. But only with the StringDeserializer i get a result on topic json-test and strin-test.
With the io.confluent.kafka.serializers.KafkaAvroDeserializer and the org.apache.kafka.connect.json.JsonDeserialize i do not recieve any messages and i got no error log.



@MessageDriven(activationConfig = {
	       
	    @ActivationConfigProperty(propertyName = "clientId", propertyValue = "testClient"),
	    @ActivationConfigProperty(propertyName = "groupIdConfig", propertyValue = "testGroup"),
	    @ActivationConfigProperty(propertyName = "topics", propertyValue = "json-test,avro-test,string-test"),
	    @ActivationConfigProperty(propertyName = "bootstrapServersConfig", propertyValue = "localhost:9092"),    
	    @ActivationConfigProperty(propertyName = "autoCommitInterval", propertyValue = "10"),    
	    @ActivationConfigProperty(propertyName = "retryBackoff", propertyValue = "10"),    
	    @ActivationConfigProperty(propertyName = "keyDeserializer", propertyValue = "org.apache.kafka.common.serialization.StringDeserializer"),    
	    @ActivationConfigProperty(propertyName = "valueDeserializer", propertyValue = "org.apache.kafka.common.serialization.StringDeserializer"),    
	    @ActivationConfigProperty(propertyName = "pollInterval", propertyValue = "10"),    
	})

	
	public class KafkaMDB implements KafkaListener {
	    	
	
		@OnRecord(topics={"json-test"})
		public void getMessageJson(ConsumerRecord record) {
			System.out.println("Got record on topic json " + record);
		}
		@OnRecord(topics={"avro-test"})
		public void getMessageAbro(ConsumerRecord record) {
			System.out.println("Got record on topic avor " + record);
		}
		@OnRecord(topics={"strin-test"})
		public void getMessageAbro(ConsumerRecord record) {
			System.out.println("Got record on topic string " + record);
		}

**Comment by MrConjurer** [comment]
Hi,

so now ist works with json and afro.
in avro i forgott the this:
@ActivationConfigProperty(propertyName = "additionalProperties", propertyValue = "schema.registry.url=http://registry:8081")
and with json i am not sure what was not correct.
Is there any way to get an exception or an log entry why the connector don't can not connect or read messages from the topic?

**Comment by peteral** [comment]
Hi,

nice that you found your solution, this one is tricky... Took me some time reading the code until I figured this trick out.

The JCA connector delegates all work to the Kafka Consumer Client. 

The Kafka Consumer Client has two options for diagnostics:
* JMX Beans - see (https://kafka.apache.org/documentation/#monitoring)
* logging - the client uses log4j, so you will need to configure it in your app (see https://logging.apache.org/log4j/2.x/manual/configuration.html)
