### ISSUE TITLE
Support CompletionStage in Kafka send methods

### ISSUE THREAD

**Issue by OndroMih** [payara/Cloud-Connectors#58]
In https://github.com/payara/Cloud-Connectors/blob/master/Kafka/KafkaJCAAPI/src/main/java/fish/payara/cloud/connectors/kafka/api/KafkaConnection.java, the `send` methods accept a callback and return a future. Since this project requires Java 8, it's much more convenient to return [CompletionStage](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletionStage.html) instead of `Future`.

Please change the return type to CompletionStage so that callbacks can be fluently added like this:

```
CompletionStage<RecordMetadata> afterSend = conn.send(new ProducerRecord(topicName, value);
afterSend.thenAccept(metadata -> { ...})
                .exceptionally(e -> {...});
```

**Comment by peteral** [comment]
The CompletionStage really is nice, but that is one of the Connector's API methods. Changing it means a broken build for everyone using the Connector (and using the return value of send of course).

I don't think the CompletionStage brings so much benefit for it to be a good trade-off.

**Comment by smillidge** [comment]
It is actually mirroring the Kafka Producer api which returns a Future

**Comment by fturizo** [comment]
Old issue that seems abandoned. Closed.
