### ISSUE TITLE
Clarify OnRecord#matchOtherMethods semantics

### ISSUE THREAD

**Issue by ggam** [payara/Cloud-Connectors#60]
The `matchOtherMethods` property of `OnRecord` and `OnRecords` annotations is very vague:

```
    /**
     * If set to true other methods on the KafkaListener class will be called
     * if they also match the topic as well as this annotated method
     * If set to false (the default) other methods will not be tested to see if they
     * have matching annotations.
     * @return 
     */
```

Looking at the relevant code, what it does when set to false is:
* Iterate through the `@OnRecords` methods in declaration order and call them. After the `WorkManager` accepts the request to send the message, check whether the annotation has `matchOtherMethods` set to false and if so, stop processing.
* If no `@OnRecords(matchOtherMethods=false)`, repeat the process for `@OnRecord` methods.

In my opinion, illegal combinations should be detected and its methods ignored with a warning, or the deployment be failed. That means only one method might be annotated `matchOtherMethods=false` for a given topic. When a method with no topics is `matchOtherMethods=false`, no other listener threads might be declared on that class.

**Comment by smillidge** [comment]
yeah it is probably a nice to have to be honest and needs more explanation. I doubt many people will use it.

**Comment by fturizo** [comment]
Old issue that seems abandoned. Closed. If the issues are still present, please raise a request in the [Ecosystem Support repository](https://github.com/payara/ecosystem-support)
