### ISSUE TITLE
Error in interface name declaration in SendKafkaMessage class

### ISSUE THREAD

**Issue by srinivasev** [payara/Cloud-Connectors#62]
Please update the code - 

//interfaceName = "fish.payara.cloud.connectors.kafka.KafkaConnectionFactory",
  interfaceName = "fish.payara.cloud.connectors.kafka.api.KafkaConnectionFactory",

Incorrect class path for KafkaConnectionFactory

**Comment by jGauravGupta** [comment]
Created ticket **AC-35** to address it.
