### ISSUE TITLE
How to limit the number of instances for KafkaMDB

### ISSUE THREAD

**Issue by srinivasev** [payara/Cloud-Connectors#63]
I need to limit the number of invocations for KafkaMDB constructor.

public KafkaMDB() {
System.out.println("KafkaMDB deployment count");
    }

Currently, I am looking the above line printed for each message/record consumed. Let me know how to have a single MDB instance capable of reading the consumer records published.

**Comment by smillidge** [comment]
There will be a new Synch mode which can be used to process all messages on a single thread with a single MDB
