### ISSUE TITLE
Message Bean Resources exceeded for message bean

### ISSUE THREAD

**Issue by gustoneves** [payara/Cloud-Connectors#67]
Currently I'm implementing a producer and a consumer with Payara Micro to transfer some information between microservices, and I'm using HiveMQ as a broker. I'm also using MQTT Cloud Connectors. The problem is when receiving some of the messages I get this Exception

 ` javax.resource.spi.UnavailableException
bdqv-consumer_1  |      at com.sun.enterprise.connectors.inbound.ConnectorMessageBeanClient.createEndpoint(ConnectorMessageBeanClient.java:462)
bdqv-consumer_1  |      at com.sun.enterprise.connectors.inbound.ConnectorMessageBeanClient.createEndpoint(ConnectorMessageBeanClient.java:406)
bdqv-consumer_1  |      at fish.payara.cloud.connectors.mqtt.api.inbound.MQTTWork.run(MQTTWork.java:88)
bdqv-consumer_1  |      at com.sun.enterprise.connectors.work.OneWork.doWork(OneWork.java:107)
bdqv-consumer_1  |      at com.sun.corba.ee.impl.threadpool.ThreadPoolImpl$TaskRunner.run(ThreadPoolImpl.java:189)
bdqv-consumer_1  |      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
bdqv-consumer_1  |      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
bdqv-consumer_1  |      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
bdqv-consumer_1  |      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
bdqv-consumer_1  |      at java.lang.Thread.run(Thread.java:748)
bdqv-consumer_1  | Caused by: org.glassfish.ejb.api.ResourcesExceededException: Message Bean Resources exceeded for message bean bdqv-consumer:MqqtBroker
bdqv-consumer_1  |      at org.glassfish.ejb.mdb.MessageBeanContainer.createMessageBeanListener(MessageBeanContainer.java:666)
bdqv-consumer_1  |      at com.sun.enterprise.connectors.inbound.ConnectorMessageBeanClient.createEndpoint(ConnectorMessageBeanClient.java:456)
bdqv-consumer_1  |      ... 9 more
bdqv-consumer_1  | ]]`

Apparently, the pool reaches its limit and one exception is thrown, but the biggest problem is that HiveMQ broker is not notified of the failure and doesn't try to resend. Could this be a miss configuration of the Message Driven Bean pool size?

**Comment by smillidge** [comment]
I think the bean pool size is too small. Have you configured the Resource Adapter min-pool-size and max-pool-size in the resource adapter?

**Comment by gustoneves** [comment]
Hi Steve, I didn't increase the pool size ...
The MDB configurations are like this 
`@MessageDriven(activationConfig = {
        @ActivationConfigProperty(propertyName = "serverURIs", propertyValue = "tcp://hivemq:1883"),
        @ActivationConfigProperty(propertyName = "cleanSession", propertyValue = "false"),
        @ActivationConfigProperty(propertyName = "automaticReconnect", propertyValue = "true"),
        @ActivationConfigProperty(propertyName = "filePersistence", propertyValue = "false"),
        @ActivationConfigProperty(propertyName = "connectionTimeout", propertyValue = "30"),
        @ActivationConfigProperty(propertyName = "clientId", propertyValue = "clientUserName"),
        @ActivationConfigProperty(propertyName = "keepAliveInterval", propertyValue = "5"),
        @ActivationConfigProperty(propertyName = "topicFilter", propertyValue = "topic/#"),
        @ActivationConfigProperty(propertyName = "qos", propertyValue = "2")
})
public class MqttBroker implements MQTTListener`

Any ideas how I need to configure it? 

I already added an _glassfish-ejb-jar.xml_ file but it didn't have any effect.

**Comment by smillidge** [comment]
Configuration via ActivationConfigProperties should work. 
I think you will need to increase the  number of MDBs available. The code is creating an endpoint for each message received and this is exceeding the number of MDBs.


When there is a resource exception this is not being propagated back to the MQTT broker hence the message is not being redelivered.

**Comment by gustoneves** [comment]
Thanks Steve, this saved our day!
