### ISSUE TITLE
Re-subscribing to mqtt topic

### ISSUE THREAD

**Issue by stevegrbr82** [payara/Cloud-Connectors#71]
When connection is lost to the message broker and restored, automaticReconnect works as expected except that the client is not longer subscribed to the relevant topic.

The message listener does not receive any further messages after paho reconnects

**Comment by stevegrbr82** [comment]
https://github.com/eclipse/paho.mqtt.java/issues/493

**Comment by stevegrbr82** [comment]
just follow this https://stackoverflow.com/questions/33735090/java-eclipse-paho-implementation-auto-reconnect

**Comment by stevegrbr82** [comment]
Ok, Paho reconnects and subscribes correctly using the client.setCallBack method but MQTT does not

**Comment by smillidge** [comment]
sorry I don't understand your last comment.

**Comment by stevegrbr82** [comment]
The Paho client has a setCallback method. The callback is called upon reconnection which allows for resubscribing to the mq queue/topic.

A stand-alone Paho java SE client will reconnect and resubscribe to a mq topic when the mq broker is available again. (when setCallback is implemented)

In a Java ee container (glassfish 5.1) the MQTT rar reconnects but does not resubscribe to the topic/queue is was subscribed to before the broker went down. 

I tested having the MQTT rar and a simple MDB deployed in glassfish5.1. Then I stop and start activemq.

**Comment by smillidge** [comment]
Reconnect seems to work correctly with resubscribing when running against Mosquitto.

I will look at the resubscribing logic.

**Comment by smillidge** [comment]
Fixed by #74

**Comment by Netskeh** [comment]
Hello, thank you a lot for providing this fix! Do you have any plans on when a new release containing this will happen?
