### ISSUE TITLE
[Kafka] Allow more flexible topic filtering

### ISSUE THREAD

**Issue by lukesrepo** [payara/Cloud-Connectors#79]
Currently, either through annotation, or though the ejb-jar.xml one has to hardcode the topics consumed. 

It would be great to have an option to define and provide those through some env-variable, or user defined Payara System Properties for all containerized env. 

Thanks in advance!

**Comment by smillidge** [comment]
Have you tried ${ENV=xxx} in the ActivationConfigProperty it should work on Payara or for System Properties just ${XXX}

**Comment by lukesrepo** [comment]
Yep, the recognition of the ENV variables might be fixed in https://github.com/flowlogix/Payara/commit/6527abac0d7b5b57184869c52cbf81d95413be0e, but that does not adress the anotations defined in fish.payara.cloud.connectors.kafka.api. Thus the following annotation
@OnRecord(topics = {"${ENV=kafka.consumer.topic}"})
would mean consuming the topic with the name "${ENV=kafka.consumer.topic}", that does not correspond to [Kafka topic naming convetion](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/internals/Topic.java#L75). So the app gets deployed, but the [line in KafkaSyncWorker](https://github.com/payara/Cloud-Connectors/blob/master/Kafka/KafkaJCAAPI/src/main/java/fish/payara/cloud/connectors/kafka/inbound/KafkaSynchWorker.java#L139) never gets resolved to true.

**Comment by smillidge** [comment]
OK I understand the use case now

**Comment by fturizo** [comment]
Old issue that seems abandoned. Closed. If the issues are still present, please raise a request in the [Ecosystem Support repository](https://github.com/payara/ecosystem-support)
