### ISSUE TITLE
[Clarification][Kafka]SASL/SSL Additional Properties

### ISSUE THREAD

**Issue by lukesrepo** [payara/Cloud-Connectors#84]
Currently, the only option to provide thesettings for  Keytab/SSL Authentication for the consumer is to use the [addtionalProperties](https://github.com/payara/Cloud-Connectors/blob/master/Kafka/KafkaJCAAPI/src/main/java/fish/payara/cloud/connectors/kafka/inbound/KafkaActivationSpec.java#L372) Activation Spec. 

If one would like to define the location of the keytab/(keystore,truststore) for Kafka Authentication infrastructure agnostic throught the env variables, then the [AddtionalPropertiesParser](https://github.com/payara/Cloud-Connectors/blob/master/Kafka/KafkaJCAAPI/src/main/java/fish/payara/cloud/connectors/kafka/tools/AdditionalPropertiesParser.java#L73) would also have to be enhanced with the support of the env variables. 

Another possible otion would be to pack the JKS files to the application resources, and retrieve them   through the classloader. 

What would be the recommened approach from your side? 
Thanks in advance!

P.S.:
Ideally one could also think about defining additional Activation Specs for the authentication, and utiliying the existing ENV resolvment for the passphrases for the JKS files.

**Comment by smillidge** [comment]
I think additional Activtion Specs is the better long term way to go. Can you suggest some?

**Comment by lukesrepo** [comment]
Thanks, personally I also prefer the ActivationSpec enchansment approach.
I would suggest two new fields in KafkaActivationSpec : **securityProtocol** and **securityConfig** in  [KafkaActivationSpec](https://github.com/payara/Cloud-Connectors/blob/0.5.0/Kafka/KafkaJCAAPI/src/main/java/fish/payara/cloud/connectors/kafka/inbound/KafkaActivationSpec.java) class.

The **securityProtocol**  field is then a concrete binding on the SecurityProtocol enum provided by [Kafka-Clients lib](https://github.com/apache/kafka/blob/2.1.1/clients/src/main/java/org/apache/kafka/common/security/auth/SecurityProtocol.java). Depending on the value of the parsed Enum value, there should be corresponding implementations of _SecurityConfigParser_(s) in the new “[fish.payara.cloud.connectors.kafka.security](https://github.com/payara/Cloud-Connectors/tree/master/Kafka/KafkaJCAAPI/src/main/java/fish/payara/cloud/connectors/kafka/)” package. 


That parser should then work with the value of additional ActivationSpec – “securityConfig”, and have the Lifecycle of something similar to:
1)	Reuse the AdditionalPropertiesParser and try to parse the instance of java.util.Properties from the value of **securityConfig**
2)	Iterate over those properties and do the substitution by utilizing the com.sun.enterprise.deployment. EnvironmentProperty class, resulting into the additional properties
3)	Those resulting properties are then merged into the actual config in the [getConsumerProperties ](https://github.com/payara/Cloud-Connectors/blob/0.5.0/Kafka/KafkaJCAAPI/src/main/java/fish/payara/cloud/connectors/kafka/inbound/KafkaActivationSpec.java#L211)method 

P.S.: The suggested approach would allow the mentioned enchantment for Inbould as well as for Outbound endpoins, as the Kafka Producer uses the  resulting config during initialization of the [Sender](https://github.com/apache/kafka/blob/2.1.1/clients/src/main/java/org/apache/kafka/clients/producer/KafkaProducer.java#L437), and the Consumer directly in its [constructor](https://github.com/apache/kafka/blob/2.1.1/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java#L718).

**Comment by lukesrepo** [comment]
At that point I have made it working with additional properties, and still have to add some components.
Currently have to concentrate on getting the data transported in this project. Could be I get to this additional feature  at the end of February.

**Comment by joackson** [comment]
I need three more options to kafka: security.protocol, ssl.truststore.location and ssl.truststore.password. Is there a deadline to release a feature with this options?

**Comment by smillidge** [comment]
No deadlines, this is open source. I'm sure @lukesrepo wouldn't mind if you beat him with a PR :-)

**Comment by fturizo** [comment]
Old issue that seems abandoned. Closed. If the issues are still present, please raise a request in the [Ecosystem Support repository](https://github.com/payara/ecosystem-support). You can still make a PR in this repository if you want to contribute it.
